# Generated by Django 4.1.1 on 2022-09-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("translators", "0001_initial"),
        ("github_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255, unique=True)),
                (
                    "prs",
                    models.ManyToManyField(blank=True, to="github_manager.pullrequest"),
                ),
                ("translators", models.ManyToManyField(to="translators.translator")),
            ],
        ),
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.CharField(max_length=255)),
                ("score", models.IntegerField(default=1)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="translate.word"
                    ),
                ),
            ],
        ),
    ]
