# Generated by Django 4.1.6 on 2023-02-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={"ordering": ("section", "sentence")},
        ),
        migrations.AlterUniqueTogether(
            name="sentence",
            unique_together={("section", "sentence")},
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="context",
        ),
    ]
