# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255, unique=True)),
                ("is_checked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="UserTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=255)),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translation.word",
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "translation"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translation.word",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "translation"),
                "abstract": False,
            },
        ),
    ]
